Add Cheat Sheet
carpentries-incubator/advanced-git pull request #23
Opened 2024-11-14 11:04 UTC by cknuepfer

Solves #20

2024-11-14 11:31 UTC, rgaiacs requested changes
Minor changes. Looks good to me.

2024-11-14 11:31 UTC, rgaiacs commented on _extras/cheatsheet.md
> +| file `.gitignore`                          | contains files ignored by Git<br>each line can contain a file name or patterns like `*.log` which will ignore all files ending with `.log` |
We should use `cat` instead of file.

2024-11-14 11:31 UTC, rgaiacs commented on _extras/cheatsheet.md
> +| `git clone <<repository>`                  | clones an existing repository                                                                                                               |
Extra `<`.

2024-11-14 11:31 UTC, rgaiacs commented on _extras/cheatsheet.md
> +| `git remote set-url <name> <newurl>` | changes URL of remote `<name>` to `<newurl>`            |
Replace `newurl` with `new-url` to match the style used in the other commands.

2024-11-21 02:24 UTC, merged

2024-11-21 02:24 UTC, ivastar commented
Thank you for your contribution @cknuepfer!